Check differently.

diff --git a/update-my-git b/update-my-git
--- a/update-my-git
+++ b/update-my-git
@@ -5,9 +5,15 @@
 ## - Check if git is installed.
 ## - Clean this mess.
 
+## Set colors.
+BOLD="\e[1m"
 GREEN="\e[32m"
 RED="\e[31m"
-RC="\e[0m"
+BLUE="\e[34m"
+
+WARN="${RED}${BOLD} [-]${RC}"
+INFO="${BLUE}${BOLD} [*]${RC}"
+GOOD="${GREEN}${BOLD} [+]${RC}"
 
 CWD=$(pwd)
 USER_HOME="/home/lespink"
@@ -19,7 +25,7 @@ UPDATE_GIT()
 				for GIT_PATH in $(find ${REPOS_LOCATION} -type d -name ".git" 2>/dev/null)
 					do
 						cd ${GIT_PATH}
-						echo -e "\n${BLUE}${BOLD}${GIT_LOCATION}${RC}"
+						echo -e "\n${INFO}${GIT_LOCATION}"
 						cd ..
 						git config pull.rebase false
 						## Pull change
@@ -41,13 +47,15 @@ UPDATE_GIT()
 						done
 }
 
-which git >/dev/null
-
-if [[ ${?} -eq "0" ]]
+REQUIREMENTS="git"
+if ! which ${REQUIREMENTS} > /dev/null
 	then
+ 		echo -e "${WARN}To run this program, you need the following packages installed: ${REQUIREMENTS}\n${WARN}Exiting..."
+		exit 1
+	else
 		if [ "$EUID" -ne 0 ]
 			then
-				echo -e "${RED}This script must be run as root!\nExiting...${RC}"
+				echo -e "${WARN}This script must be run as root!\nExiting..."
 				exit 1
 			else
 				if [[ -f ${USER_HOME}/.git-credentials ]]
@@ -77,11 +85,8 @@ if [[ ${?} -eq "0" ]]
 						ln -svf /opt/My-Repo/Crypto/* /usr/local/bin
 
 					else
-						echo -e "${RED}Git credentials not found!\nExiting...${RC}"
+						echo -e "${WARN}Git credentials not found!\nExiting..."
 						exit 1
 				fi
 		fi
-	else
-		echo -e "${RED}Git isn't installed on this system!\nExiting...${RC}"
-		exit 1
 fi
