Function+check if git is installed

diff --git a/update-my-git b/update-my-git
--- a/update-my-git
+++ b/update-my-git
@@ -13,15 +13,8 @@ CWD=$(pwd)
 USER_HOME="/home/lespink"
 REPOS_LOCATION="/opt/My-Repo/"
 
-## Check if root
-if [ "$EUID" -ne 0 ]
-	then
-		echo -e "${RED}This script must be runned as root!${RESET_COLOR}"
-		exit 1
-	else
-		if [[ -f ${USER_HOME}/.git-credentials ]]
-			then
-				cd ${REPOS_LOCATION}
+function UPDATE_GIT()
+{
 				## Search for GIT repos.
 				for GIT_PATH in $(find ${REPOS_LOCATION} -type d -name ".git" 2>/dev/null)
 					do
@@ -55,8 +48,25 @@ if [ "$EUID" -ne 0 ]
 						ln -svf /opt/My-Repo/Utilities/* /bin/
 						ln -svf /opt/My-Repo/Wallpapers-Management/* /bin/
 				done
-			else
-				echo -e "${RED}Git credentials not found!${RESET_COLOR}"
-		fi
-fi
+}
 
+which git >/dev/null
+
+if [[ ${?} -eq "0" ]]
+	then
+		if [ "$EUID" -ne 0 ]
+			then
+				echo -e "${RED}This script must be run as root!${RESET_COLOR}"
+				exit 1
+			else
+				if [[ -f ${USER_HOME}/.git-credentials ]]
+					then
+						cd ${REPOS_LOCATION}
+						UPDATE_GIT
+					else
+						echo -e "${RED}Git credentials not found!${RESET_COLOR}"
+				fi
+		fi
+	else
+		echo -e "${RED}Git isn't installed on this system${RESET_COLOR}"
+fi
