Minor changes.

diff --git a/update-my-git b/update-my-git
--- a/update-my-git
+++ b/update-my-git
@@ -56,7 +56,7 @@ if [[ ${?} -eq "0" ]]
 	then
 		if [ "$EUID" -ne 0 ]
 			then
-				echo -e "${RED}This script must be run as root!${RESET_COLOR}"
+				echo -e "${RED}This script must be run as root!\nExiting...${RESET_COLOR}"
 				exit 1
 			else
 				if [[ -f ${USER_HOME}/.git-credentials ]]
@@ -64,9 +64,11 @@ if [[ ${?} -eq "0" ]]
 						cd ${REPOS_LOCATION}
 						UPDATE_GIT
 					else
-						echo -e "${RED}Git credentials not found!${RESET_COLOR}"
+						echo -e "${RED}Git credentials not found!\nExiting...${RESET_COLOR}"
+						exit 1
 				fi
 		fi
 	else
-		echo -e "${RED}Git isn't installed on this system${RESET_COLOR}"
+		echo -e "${RED}Git isn't installed on this system!\nExiting...${RESET_COLOR}"
+		exit 1
 fi
