- link

diff --git a/update-my-git b/update-my-git
--- a/update-my-git
+++ b/update-my-git
@@ -1,6 +1,5 @@
 #!/bin/bash
-
-## Update my git REPOitory.
+## Update my git repositories.
 
 RC="\e[0m"
 GREEN="\e[32m"
@@ -8,116 +7,66 @@ RED="\e[31m"
 ORANGE="\e[33m"
 BLUE="\e[34m\e[1m"
 
-CWD=$(pwd)
-USER_HOME="/home/$( ls /home | head -n 1 )"
-
-OK=' '
-INFO=' '
-WARN=' '
-FOLDER=' '
+OK="${GREEN} "
+INFO="${ORANGE} "
+WARN="${RED} "
+FOLDER="${BLUE} "
 
 
-updateGit()
+updateGit() {
 
-{
-
+	USER_HOME="/home/$( ls /home | head -n 1 )"
 	REPO_PATH="/opt/mygit"
 	REPO_FOUND=( $( find "${REPO_PATH}/" -type d -name ".git" 2>/dev/null ) )
 
 	echo -e "\n${ORANGE}${INFO} Looking for git repositories...${RC}"
 
+    for REPO in "${REPO_FOUND[@]}"; do
 
-    for REPO in "${REPO_FOUND[@]}"
-        do
+        CURRENT_REPO_NAME=$( echo "${REPO}" | cut -d '/' -f 4 )
 
-            CURRENT_REPO_NAME=$( echo "${REPO}" | cut -d '/' -f 4 )
+        echo -e "\n${BLUE}${FOLDER} ${CURRENT_REPO_NAME} ${RC}"
+        cd "${REPO}" && cd .. || return
 
-            echo -e "\n${BLUE}${FOLDER} ${CURRENT_REPO_NAME} ${RC}"
-            cd "${REPO}" && cd ..
-
-            git pull ## Will return error if changes have been made.
-            git config pull.rebase true
-
-            git add -v .* 2>/dev/null ## Dismiss error due to ".." being added
-            git add -v * 2>/dev/null ## ``
-
-            git commit -a && git push -v
-
-            git pull && echo -e "\n${GREEN}${OK} ${CURRENT_REPO_NAME} Updated. ${RC}\n\n"
+        git config pull.rebase true
+        git pull						## Will return error if changes have been made.
+        git add -v .* * 2>/dev/null		## Dismiss error due to ".." being added.
+        git commit -a && git push -v
+        git pull && echo -e "\n${OK}${CURRENT_REPO_NAME} Updated. ${RC}\n"
 
     done
 
 }
 
 
-makeLink()
+checkGitInstall() {
 
-{
+    if ! which git>/dev/null; then
 
-    cd "${REPO_DIR}"
+        echo "\n${WARN}Git is not installed on this system! ${RC}"
+        exit 1
 
-    ## Dot-files.
-    ln -svf ${REPO_DIR}/Configs/dot-files/.* ${USER_HOME} 2>/dev/null
-
-    ## Rofi config
-    [[ -d ${REPO_DIR}/Configs/rofi/&&-d ${USER_HOME}/.config/rofi ]]&&ln -svf ${REPO_DIR}/Configs/rofi/* ${USER_HOME}/.config/rofi
-
-    ## Custom GTK CSS.
-    [[ -f ${REPO_DIR}/Configs/gtk.css&&-d ${USER_HOME}/.config/gtk-3.0 ]]&&ln -svf ${REPO_DIR}/Configs/gtk.css ${USER_HOME}/.config/gtk-3.0
-
-    ## Nanorc files.
-    [[ -d ${REPO_DIR}/nanorc ]]&&ln -svf ${REPO_DIR}/nanorc /usr/share/nanorc
+    fi
 
 
-    ## Link scripts.
-    [[ -d ${REPO_DIR}/Updating ]]&&ln -svf ${REPO_DIR}/Updating/* /usr/local/bin
-    [[ -d ${REPO_DIR}/Utilities ]]&&ln -svf ${REPO_DIR}/Utilities/* /usr/local/bin
-    [[ -d ${REPO_DIR}/Telebash ]]&&ln -svf ${REPO_DIR}/Telebash/* /usr/local/bin
-    [[ -d ${REPO_DIR}/Crypto ]]&&ln -svf ${REPO_DIR}/Crypto/* /usr/local/bin
+    if [[ ! -f ${HOME}/.git-credentials ]]; then
 
-    ## Xfce4 files.
-    [[ -d ${USER_HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/ && -e /opt/mygit/Configs/xfce/xfce4-keyboard-shortcuts.xml ]]&&ln -svf /opt/mygit/Configs/xfce/xfce4-keyboard-shortcuts.xml ${USER_HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/
+        echo -e "\n${WARN}Git credentials not found! ${RC}"
+        exit 1
+
+    fi
 
 }
 
 
-checkGitInstall()
+main() {
 
-{
-    if ! which git>/dev/null
-        then
+    if [[ ${EUID} -ne "0" ]]; then
 
-            echo "\n${RED}${WARN} Git is not installed on this system! ${RC}"
-            exit 1
+        echo -e "\n${WARN}Run me as root! ${RC}"
+        exit 1
 
     fi
-
-
-    if [[ ! -f ${HOME}/.git-credentials ]]
-        then
-
-            echo -e "\n${RED}${WARN} Git credentials not found! ${RC}"
-            exit 1
-
-    fi
-
-
-
-}
-
-
-main()
-
-{
-
-    if [[ ${EUID} -ne "0" ]]
-        then
-
-            echo -e "\n${RED}${WARN} Run me as root! ${RC}"
-            exit 1
-
-    fi
-
 
     checkGitInstall && updateGit
     makeLink 1>/dev/null
@@ -125,17 +74,17 @@ main()
 }
 
 
-if main
+CWD="$(pwd)"
 
-    then
+if main; then
 
-        echo -e "\n${GREEN}${OK} Git Repositories have been updated successfully! ${RC}"
-        cd ${CWD}
-        exit
+	echo -e "\n${OK}Git Repositories have been updated successfully! ${RC}"
+	cd ${CWD}
+	exit
 
-    else
+else
 
-        echo -e "\n${RED}${WARN} Something went wrong! ${RC}"
-        exit 1
+    echo -e "\n${WARN}Something went wrong! ${RC}"
+    exit 1
 
 fi
